name = "checkdocument"
main = "worker.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pea-document-db"
database_id = "ffa25784-2ac9-4080-a437-237a08c740ad"
